version: '3.1'

services:
  postgres:
    container_name: ${DATABASE_NAME}_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
volumes:
  postgres:
